name: Build & Push to ECR

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  AWS_REGION: eu-central-1
  ECR_REGISTRY: 787587782604.dkr.ecr.eu-central-1.amazonaws.com
  ECR_REPOSITORY_BACKEND: gm-diploma-project-ecr-api
  ECR_REPOSITORY_FRONTEND: gm-diploma-project-ecr-frontend
  ROLE_TO_ASSUME: arn:aws:iam::787587782604:role/GitHubActions
  ARGOCD_REPO: github.com/MartinovG/DiplomaProject-ArgoCD.git
  ARGOCD_FILE_PATH: eu-central-1/prod/helm/values.yaml

permissions:
  id-token: write 
  contents: read

jobs:
  build-and-push:
    name: Build & Push Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Calculate Image Tag
        id: meta
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "TAG=pr-${{ github.event.number }}" >> $GITHUB_ENV
          else
            echo "TAG=sha-${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Build Backend
        run: |
          cd backend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:backend-${{ env.TAG }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:backend-${{ env.TAG }}

      - name: Build Frontend
        run: |
          cd frontend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:frontend-${{ env.TAG }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:frontend-${{ env.TAG }}

      - name: Update ArgoCD Repo
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.ARGOCD_REPO_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          git clone https://x-access-token:${GH_TOKEN}@${ARGOCD_REPO} argocd-repo
          cd argocd-repo

          sed -i "s|tag: backend-.*|tag: backend-${{ env.TAG }}|" ${{ env.ARGOCD_FILE_PATH }}
          sed -i "s|tag: frontend-.*|tag: frontend-${{ env.TAG }}|" ${{ env.ARGOCD_FILE_PATH }}

          git diff

          if [[ -n $(git status -s) ]]; then
            git add ${{ env.ARGOCD_FILE_PATH }}
            git commit -m "ci: update production images to ${{ env.TAG }}"
            git push origin main
            echo "ArgoCD repository updated successfully!"
          else
            echo "No changes detected (tags might be identical)."
          fi