name: Build & Push to ECR

on:
  push:
    branches: [ "main", "gcp"]
  pull_request:

env:
  GCP_REGION: europe-west3
  REGISTRY: europe-west1-docker.pkg.dev/playground-s-11-a2f0baaf/gm-diploma-project
  ARGOCD_REPO: github.com/MartinovG/DiplomaProject-ArgoCD.git
  ARGOCD_FILE_PATH: europe-west3/prod/helm/values.yaml

permissions:
  id-token: write 
  contents: read

jobs:
  build-and-push:
    name: Build & Push Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/845306284109/locations/global/workloadIdentityPools/github-actions-pool-v2/providers/github-actions-provider-v2
          service_account: github-actions-ci@playground-s-11-a2f0baaf.iam.gserviceaccount.com
      
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Calculate Image Tag
        id: meta
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            SHORT_SHA=$(echo "${{ github.event.pull_request.head.sha }}" | cut -c1-8)
            echo "TAG=pr-${{ github.event.number }}-${SHORT_SHA}" >> $GITHUB_ENV
          else
            echo "TAG=sha-${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Check Existing Images
        id: check
        run: |
          if aws ecr describe-images \
              --repository-name "$REGISTRY" \
              --image-ids imageTag="backend-${{ env.TAG }}" \
              --region "$AWS_REGION" >/dev/null 2>&1; then
            echo "backend_exists=true" >> $GITHUB_OUTPUT
          else
            echo "backend_exists=false" >> $GITHUB_OUTPUT
          fi

          if aws ecr describe-images \
              --repository-name "$REGISTRY" \
              --image-ids imageTag="frontend-${{ env.TAG }}" \
              --region "$AWS_REGION" >/dev/null 2>&1; then
            echo "frontend_exists=true" >> $GITHUB_OUTPUT
          else
            echo "frontend_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build Backend
        if: steps.check.outputs.backend_exists == 'false'
        run: |
          cd backend
          docker build -t $REGISTRY/backend:backend-${{ env.TAG }} .
          docker push $REGISTRY/backend:backend-${{ env.TAG }}

      - name: Build Frontend
        if: steps.check.outputs.frontend_exists == 'false'
        run: |
          cd frontend
          docker build -t $REGISTRY/frontend:frontend-${{ env.TAG }} .
          docker push $REGISTRY/frontend:frontend-${{ env.TAG }}

      - name: Update ArgoCD Repo
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.ARGOCD_REPO_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          git clone https://${GITHUB_ACTOR}:${GH_TOKEN}@${ARGOCD_REPO} argocd-repo
          cd argocd-repo

          sed -i "s|tag: backend-.*|tag: backend-${{ env.TAG }}|" ${{ env.ARGOCD_FILE_PATH }}
          sed -i "s|tag: frontend-.*|tag: frontend-${{ env.TAG }}|" ${{ env.ARGOCD_FILE_PATH }}

          git diff

          if [[ -n $(git status -s) ]]; then
            git add ${{ env.ARGOCD_FILE_PATH }}
            git commit -m "ci: update production images to ${{ env.TAG }}"
            git push origin main
            echo "ArgoCD repository updated successfully!"
          else
            echo "No changes detected (tags might be identical)."
          fi